---
$schema: "http://json-schema.org/draft-06/schema#"
description: "Schema for the configfile."
general:
  already_assembled:
    default: false
    description: "Skipping of the quality control and read assembly steps for data that is already assembled."
    type: boolean
  cores:
    default: 4
    description: "Amount of cores available for the workflow."
    exclusiveMinimum: 0
    type: int
  demultiplexing:
    default: false
    description: "Demultiplexing for reads that were not demultiplexed by the sequencing company (slow)."
    type: boolean
  filename:
    default: project
    description: "The filename of the project folder, primertable (.csv) and config file (.yaml)."
    type: string
  primertable:
    default: project.csv
    description: "Path to the primertable."
    type: string
  read_sorting:
    default: false
    description: "Read sorting for paired end reads that were not sorted by the sequencing company (slow)."
    type: boolean
  units:
    default: units.tsv
    description: "Path to the sequencing unit sheet."
    type: string
  name_ext:
    default: R1
    description: "The identifier for the forward read (for the reverse read the 1 is switched with 2, if the data is in paired-end format), has to be included at the end of the file name, before the file format identifier (including for single end files)."
    type: string
  paired_End:
    default: true
    description: "The format of the sequencing data, TRUE if the reads are in paired-end format."
    type: boolean
qc:
  all_primer:
    default: true
    description: "Boolean that indicates if the sequence is free of any kind of additional subsequences (primer, barcodes etc.)."
    type: boolean
  barcode_removed:
    default: true
    description: "Boolean that indicates if the sequence is free of barcodes."
    type: boolean
  maxlen:
    default: 600
    description: "The maximal length of a sequence after primer removal to be accepted by PANDAseq."
    minimum: 10
    type: int
  minlen:
    default: 100
    description: "The minimal length of a sequence after primer removal to be accepted by PANDAseq."
    minimum: 10
    type: int
  minoverlap:
    default: 15
    description: "Sets the minimum overlap between forward and reverse reads."
    maximum: 50
    minimum: 1
    type: int
  minqual:
    default: 1
    description: "Minimal quality score for bases in an assembled read to be accepted by PANDAseq."
    minimum: 1
    type: int
  mq:
    default: 25
    description: "Minimum quality sequence check (prinseq), filtering of sequences according to the PHRED quality score before the assembly."
    minimum: 0
    type: int
  trim_to_length:
    default: 0
    description: "(prinseq) if prinseq should trim the reads & and to what length it should trim (if 0 it doesn't trim)."
    minimum: 0
    type: int
  primer_offset:
    default: false
    description: "Using PANDAseq to remove primer sequences by length offset instead of sequence identity."
    type: boolean
  threshold:
    default: 0.9
    description: "PANDAseq score threshold a sequence must meet to be kept in the output."
    maximum: 1.0
    minimum: 0.0
    type: float
constraint_filtering:
  constraints:
    default: ['homopolymer','undesired_subsequences','overall_gc_content','windowed_gc_content','kmer_counting']
    description: "array containing the filtering rules to be applied"
    type: array,
    items: {
      type: "string",
      enum: ["homopolymer", "undesired_subsequences", "overall_gc_content", "windowed_gc_content", "kmer_counting"]
    }
    uniqueItems: true
  after_demultiplexing:
    default: false
    description: "filter after demultiplexing"
    type: boolean
  after_quality_control:
    default: false
    description: "filter after quality control"
    type: boolean
  after_assembly:
    default: false
    description: "filter after assembly"
    type: boolean
  inplace_repair:
    default: false
    description: "if set: invalid sequences will be replaced with the repaired ones, if not set: append original sequences"
    type: boolean
  maximum_repair_cycles:
    default: 100
    description: "maximum number of single base-repairs per sequence before a sequence will be treated as FAILED"
    type: int
  repair_quality_score:
    default: 33
    description: "phread quality score to set after a repair"
    type: int
  repair_after_demultiplexing:
    default: false
    description: "repair after demultiplexing"
    type: boolean
  repair_after_quality_control:
    default: false
    description: "repair after quality control"
    type: boolean
  repair_after_assembly:
    default: false
    description: "repair after assembly"
    type: boolean
  homopolymer:
    count:
      default: 5
      description: "homopolymers length"
      minimum: 0
      type: int
  windowed_gc_content:
    gc_min:
      default: 0.3
      description: "gc min"
      maximum: 1.0
      minimum: 0.0
      type: float
    gc_max:
      default: 0.7
      description: "gc max"
      maximum: 1.0
      minimum: 0.0
      type: float
    window_size:
      default: 50
      description: "window size"
      minimum: 1
      type: int
  overall_gc_content:
    gc_min:
      default: 0.3
      description: "gc min"
      maximum: 1.0
      minimum: 0.0
      type: float
    gc_max:
      default: 0.7
      description: "gc max"
      maximum: 1.0
      minimum: 0.0
      type: float
  undesired_subsequences:
    file:
      default: 'scripts/constraints/undesired_subsequences.txt'
      description: "filename with undesired sequences, one per line"
      type: string
  kmer_counting:
    k:
      default: 20
      description: "kmer"
      minimum: 1
      type: int
    upper_bound:
      default: 2
      description: "upper bound"
      minimum: 0
      type: int
derep:
  clustering_id:
    default: 1.0
    description: "clustering threshold for vsearch derep"
    maximum: 1.0
    minimum: 0.1
    type: float